pipeline {
    agent { label 'chethan' }

    environment {
        DOCKER_IMAGE = 'chethankumar6/expense-mysql'
        DOCKER_TAG = 'v1'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker image') {
            steps {
                bat """
                    set DOCKER_BUILDKIT=0
                    docker build -t %DOCKER_IMAGE%:%DOCKER_TAG% -f Docker-images\\mysql\\Dockerfile Docker-images\\mysql
                """
            }
        }

        stage('Push Docker image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    bat """
                        docker login -u %DOCKER_USER% -p %DOCKER_PASS%
                        docker push %DOCKER_IMAGE%:%DOCKER_TAG%
                    """
                }
            }
        }
    }
}
